language: nodejs
node_js:
  - "8"

before_script:
  - npm install -g npm@latest

install:
  - npm ci

cache:
  directories:
  - "$HOME/.npm"

script:
  - npm run lint
  - npm run test

after_script:
  - npm install coveralls --save-dev
  - npm run coverage-ci
