language: nodejs
before_install:
  - npm install -g npm@latest
install:
  - npm ci
script:
  - npm run lint
  - npm run test
after_success:
  - npm install coveralls --save-dev
  - npm run coverage-ci
