language: nodejs
node_js:
  - "8"

before_script:
  - npm install
  - npm install coveralls --save-dev

script:
  - npm run lint
  - npm run test
  - npm run coverage-ci

  after_script:
    - 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
